### ISSUE TITLE
HDF5 Issue

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/gbff#10]
As John mentioned, there might actually be an issue with the HDF5 backend.  I will look into it.

```
Sampling finished normally.
Warning, unable to save state.
Error message:
Traceback (most recent call last):
  File "/home/kyleb/opt/lib/python2.7/site-packages/pymc/Model.py", line 777, in save_state
    self.db.savestate(self.get_state())
  File "/home/kyleb/opt/lib/python2.7/site-packages/pymc/database/hdf5.py", line 503, in savestate
    cur_chain._state_[0] = state
  File "/home/kyleb/opt/lib/python2.7/site-packages/tables/vlarray.py", line 785, in __setitem__
    self._assign_values(coords, value)
  File "/home/kyleb/opt/lib/python2.7/site-packages/tables/vlarray.py", line 718, in _assign_values
    nparr[:], exc))
ValueError: Value parameter:
'array([128,   2, 125, ..., 117, 117,  46], dtype=uint8)'
cannot be converted into an array object compliant vlarray[0] row: 
'array([128,   2, 125, ..., 117, 117,  46], dtype=uint8)'
The error was: <could not broadcast input array from shape (3395) into shape (3397)>
```

**Comment by pgrinaway** [comment]
Huh, ok, I'll temporarily disable the hdf5 backend, then?

**Comment by kyleabeauchamp** [comment]
The issue can be avoided by removing the `save_interval` flag.  The link to the pymc issue is above.

**Comment by jchodera** [comment]
Might help us analyze efficiency if we save all the data anyway!
